### ISSUE TITLE
Error in Navigation with Lens 

### ISSUE THREAD

**Issue by francescogorini** [scalaquest/PPS-19-ScalaQuest#114]
Today, @corinz97, @ThomasAngeliniUnibo and I, we had an issue with player navigation between rooms.

Working on the new example, we discovered that there are some problems when the story teller want to change the location of an item. Especially, to do this it's necessary to create new rooms with the same reference.

Then, moving the player between rooms is actually made by a Lens that works with the implementation of the room, instead of the ref. For this reason, the navigation between rooms doesn't go well.

Here you can see the problem:

https://github.com/scalaquest/PPS-19-ScalaQuest/blob/80c9c364e9b4061be735d0097e4ac867321ab234/core/src/main/scala/io/github/scalaquest/core/model/behaviorBased/commons/groundBehaviors/impl/NavigableExt.scala#L49-L54

https://github.com/scalaquest/PPS-19-ScalaQuest/blob/80c9c364e9b4061be735d0097e4ac867321ab234/core/src/main/scala/io/github/scalaquest/core/model/behaviorBased/commons/reactions/CReactionsExt.scala#L48

and our solution is in  `feature/lens-fix`.

I hope I was clear as possible.

**P.s.** this problem comes out now because in the previous examples, we didn't change the location of an item between rooms.

**Comment by maldins46** [comment]
Ok nice, I've just checked the solution, and it seems alright. Well done!

The following was the actual problem: `locationRoomLens` did what it should do (change the ref), but it also something more (modify the actual room), that it was wrong.

Does this solve the problem with the example anyway?

**Comment by francescogorini** [comment]
![](https://media.giphy.com/media/SVgKToBLI6S6DUye1Y/giphy.gif)

I have to explain: the example works with the solution we suggest to this problem, anyway in branch `feature/quest-of-secrets-example` we'll use that only after your esplicit ok (which means `feature/lens-fix` merged in `dev`).

> The following was the actual problem: `locationRoomLens` did what it should do (change the ref), but it also something more (modify the actual room), that it was wrong.

This problem will be solved in next episodes.

**Comment by maldins46** [comment]
Ok we'll see tomorrow
