### ISSUE TITLE
Bug in escape room

### ISSUE THREAD

**Issue by francescogorini** [scalaquest/PPS-19-ScalaQuest#119]
Playing the escape room, I observed that this example stopped working. 

In particular, the bug is here (a self-loop in living room😕)

![image](https://user-images.githubusercontent.com/36625232/109941197-3095cf00-7cd3-11eb-959d-b92ea9b73f44.png)

**Comment by francescogorini** [comment]
The same problem is present also in the pokemon one! 

#beautifulday #enjoy #like4like

**Comment by maldins46** [comment]
I cannot reproduce the problem. Are you testing it from an old version of the project?

**Comment by francescogorini** [comment]
Yes, I probably have a big problem with my git version. 

Next: I'll close this (needless) problem. 

Next: I'll destroy git from my pc.

Next: I'll destroy my pc.

Next: I'll start to study Single Cycle Degree Programme in "Giurisprudenza".
