### ISSUE TITLE
Spotless problems

### ISSUE THREAD

**Issue by maldins46** [scalaquest/PPS-19-ScalaQuest#13]
The plugin `Spotless`, when used for Scala code formatting, has some problems recognizing the `.scalafmt.conf` file. This causes the spotlessApply/spotlessCheck tasks to use the default configuration, even if the conf file is present and, for example, used by the IntelliJ internal formatter, causing disalignment between the two.

Spotless is a big project, potentially heavy and maybe invasive for our purposes, that integrates below scalafmt when dealing with Scala. As we are at the start of the project, I propose to use the other plugin recommended in the scalafmt website, called [gradle-scalafmt](https://github.com/alenkacz/gradle-scalafmt).

**Comment by lippo97** [comment]
The only downside I see is we could use spotless to format Prolog code too. Are you sure this can't be fixed by telling Spotless to use scalafmt with a specified configuration file? 

https://github.com/diffplug/spotless/tree/main/plugin-gradle#scalafmt

**Comment by maldins46** [comment]
Of course, I initially tried setting the path inside the `scalaquest.common-conventions.gradle.kts` plugin with:

```
spotless {
    scala {
        scalafmt().configFile(rootDir.absolutePath + "/.scalafmt.conf")
    }
}
```

`rootDir.absolutePath` is required as the plugin acts inside the subproject. This fix hasn't worked initially, but re-trying now, after `gradle clean` seems to work, effectively...😅  
Can you reproduce this into your machine, as a confirmation?

**Comment by maldins46** [comment]
> The only downside I see is we could use spotless to format Prolog code too

Not sure about it... Prolog is not officially supported by Spotless. I think this couldn't be obtained without acting into Spotless library directly

**Comment by maldins46** [comment]
This is what happened initially with the correct path in Spotless, launching `./gradlew spotlessCheck`:

```
> Task :examples:escape-room:spotlessScala FAILED
Step 'scalafmt' found problem in 'examples/escape-room/src/main/scala/io/github/scalaquest/examples/escaperoom/App2.scala':
null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.diffplug.spotless.scala.ScalaFmtStep.invokeNoArg(ScalaFmtStep.java:142)
...
```

This eventually occurs sometimes, reproducing the situation. I think it is linked to files formatted in some way. But I can't understand why this happens only with a custom .scalafmt.conf file, that works with the gradle-scalafmt plugin.

**Comment by maldins46** [comment]
I found the problem.. Spotless probably do not support the latest features of scalafmt, resulting in a crash when using `newlines.source=keep` inside the `.scalafmt.conf`. When removing the line, the plugin works properly. We should decide wether to keep Spotless without this line inside the conf, or switch to the other plugin

**Comment by maldins46** [comment]
Definitely solved, setting also scalafmt version explicitly, for the plugin. Opening now a pull request with the alternative solution.
