### ISSUE TITLE
Set up delivery and deployment

### ISSUE THREAD

**Issue by maldins46** [scalaquest/PPS-19-ScalaQuest#22]
When we arrive at a quite stable version of the project, we should set up the delivery and deployment process, possibly automated with the CI, for pushes into the main branch. We are currently evaluating the release platform for the library: whether Maven Central, GitHub, or both.

**Comment by corinz97** [comment]
I discovered an integrated functionality which enables Maven publishing, it's [Github Packages.](https://github.com/features/packages). Here there is a [using-github-packages-with-github-actions](https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions) guide about generating a Docker image, and here there is a [configuring-gradle-for-use-with-github-packages](https://docs.github.com/en/packages/guides/configuring-gradle-for-use-with-github-packages) guide.
I know it's early to think about this issue but i'll post it anyway for future purposes.
