### ISSUE TITLE
Generate a single ScalaDoc for all the subprojects

### ISSUE THREAD

**Issue by lippo97** [scalaquest/PPS-19-ScalaQuest#26]
Currently we generate a ScalaDoc for each subproject. It think it would be better if we were able to aggregate all the documentation in a single big ScalaDoc.
What do you all think about it?

**Comment by maldins46** [comment]
It may be an idea of course, but it could be complex, or not correct, depending on our target.

I'll explain: If the subprojects will be released singularly as we said initially, in Maven Central or other platforms, it makes sense to keep them separated. If we are planning to release in  Maven central, there are some OS alternatives to host the Scaladoc automatically ([javadoc.io](https://javadoc.io/), for instance). Or maybe, we could also use GitHub Pages, with a dedicated branch that would host the Scaladoc artifacts, and a home page with the links to each one (easy to obtain with Jekyll)

**Comment by maldins46** [comment]
Magically completed with #65. You can see the results [here](https://scalaquest.github.io/PPS-19-ScalaQuest/).
