### ISSUE TITLE
Migrate from GitHubFlow to GitFlow

### ISSUE THREAD

**Issue by maldins46** [scalaquest/PPS-19-ScalaQuest#34]
Initially, having a single `main` branch as the work branch was useful, as the development was more agile. This is the base principle of using GitHubFlow.

Anyway, the project is now becoming more complex and structured: some release assets will be required soon to be deployed, both for reports (see #20) and libraries (see #22). Now is the perfect moment to migrate to a more structured **GitFlow**, with:
- a **stable branch**, `main`, from which releases will be generated;
- a **work branch** `dev`, as the base for incremental unstable work. 

Feature branches will then merge to the `dev`, which will merge into `main` only when a stable version is reached.

**Comment by corinz97** [comment]
That's a good idea
