### ISSUE TITLE
Reports creation

### ISSUE THREAD

**Issue by francescogorini** [scalaquest/PPS-19-ScalaQuest#45]
Hi everyone!

Today I created a new branch called `feature/reports`. Here we can write both PPS and LSS report.  

I started to write some concepts in Markdown using IntelliJ and I founded out a little (but annoying) problem. By default, IntelliJ doesn't start a new line when the window lenght is exceeded. In order to solve this problem, it's necessary to [enable "Soft-Wrap"](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009033399-How-to-enable-soft-wrap-in-IntelliJ-).

I don't know if IntelliJ is the best solution to write Markdown, but now the IDE is very friendly.

**Comment by lippo97** [comment]
I think we can even enable hard wrapping without any kind of problem, because I think that in order to separate some text in two distinct paragraphs you need to leave an empty line. If that's the case I'd stick with hard wrapping so that you can edit some Markdown without having to boot the full IDE.

**Comment by maldins46** [comment]
Nice! Anyway, it is desired that the editor does not start a new line, as the Markdown should track the content, not the appearance. The soft wrap is useful for visualization and modification.

**Comment by maldins46** [comment]
In general, to edit the markdown intensively, intellij is not really suitable. Personally, I use macDown for Mac, but there are a lot of alternatives for other systems. I'm not sure about hard wrapping anyway

**Comment by francescogorini** [comment]
Sorry guys, I didn't explain it very well. It's also possible to enable soft wrapping only in the current file. [Here](https://www.jetbrains.com/help/idea/settings-editor-general.html) you can see the solution.

**Comment by lippo97** [comment]
@maldins46 I consider Markdown files as source code files. As we don't write Scala source code in just one line (even if it would compile just fine), I think we should write readable and portable Markdown source code (this is true as long as pandoc uses an empty line to split some text in two paragraphs).

**Comment by maldins46** [comment]
Ok then 👌

**Comment by lippo97** [comment]
Pandoc allows to manage how wrapped lines work.
I leave this here just as a reference: 
https://pandoc.org/MANUAL.html#option--wrap

**Comment by maldins46** [comment]
Closing as this should be now handled in the other repo.
