### ISSUE TITLE
Dictionary and Prolog Parser refactoring

### ISSUE THREAD

**Issue by maldins46** [scalaquest/PPS-19-ScalaQuest#48]
I open this issue as a reference for these days' work.
To generate `Model`. `Parsing` and `Pipeline` main artifacts, a sort of initial "wrapper" (dictionary maybe?) is used. @scalaquest/team-2 is working on it.

**Comment by francescogorini** [comment]
Today I revised the code made yesterday by @lippo97 and I. 

This two lines below I think should be removed but If I do, the code don't compile. I offer fish and chips to 
first who answers.

https://github.com/scalaquest/PPS-19-ScalaQuest/blob/ff74c05280a82a73bc955eef611fcb85e52a7f20/core/src/main/scala/io/github/scalaquest/core/dictionary/generators/Generator.scala#L3-L4

**Comment by lippo97** [comment]
I guess this is solved now.
