### ISSUE TITLE
Small random improvements to "escape room"

### ISSUE THREAD

**Issue by lippo97** [scalaquest/PPS-19-ScalaQuest#78]
@francescogorini and I tried the escape room example and made some very little improvements (we removed an extra blank line on the inspect command and we put a little `>` symbol to simulate a command prompt).
We had some improvements in mind, but I honestly don't know how easy are they to be implemented. I'll leave them below: 

* In the case something needs an item to be opened it would be very nice if "open the _chest_" was answered with something like "I wish i had something to help me do that", so that you can understand you have to use some item on it. Like "open the _chest_ with the _key_".
* It would be nice in the case there are more than one item with the same base name, if asked to interact with one of them using an ambiguous item description (such as _apple_), the game responded with "Which _apple_?". We tried to implement that behavior and we'll soon open a pull request. 

Besides that the game seems playable and feels very interactive! 🚀

In general we could keep this issue open to report some minor changes that we think of.

**Comment by francescogorini** [comment]
"[..] the game seems playable and feels very interactive!"

![image](https://user-images.githubusercontent.com/36625232/107344517-d5e9c880-6ac2-11eb-9305-0c1139a9fe27.png)

**Comment by maldins46** [comment]
> In the case something needs an item to be opened it would be very nice if "open the chest" was answered with something like "I wish i had something to help me do that", so that you can understand you have to use some item on it. Like "open the chest with the key".

Agree, and It should not be difficult to implement, as it could be accomplished with a `FailedToOpen` message, for example, without custom modifications. We can handle in @scalaquest/team-1 easily in the next few days.

> We tried to implement that behavior and we'll soon open a pull request.

This is black magic, and you @lippo97 are the chief wizard 🧙‍♂️  Amazing!

**Comment by lippo97** [comment]
> > 
> 
> Agree, and It should not be difficult to implement, as it could be accomplished with a `FailedToOpen` message, for example, without custom modifications. We can handle in @scalaquest/team-1 easily in the next few days.

Yea something in the likes of that or even `Required(key: Key)` (so that you can later choose if you want to print the key name or not).



> This is black magic, and you @lippo97 are the chief wizard mage_man Amazing!

I really thank you @maldins46.
One small note: we tend not to use terms such as master/slave, blacklist/whitelist and so we are consider offensive _black_ magic too. We suggest you use _rainbow_ magic 🌈, instead.

**Comment by maldins46** [comment]
Partially done in #79

**Comment by maldins46** [comment]
> In the case something needs an item to be opened it would be very nice if "open the chest" was answered with something like "I wish i had something to help me do that", so that you can understand you have to use some item on it. Like "open the chest with the key".

Done in #97.
