### ISSUE TITLE
Change Effect keyword to StateUpdate?

### ISSUE THREAD

**Issue by maldins46** [scalaquest/PPS-19-ScalaQuest#8]
The keyword Effect used to refer to something that changes some values inside the state is not semantically correct, as it could be confused with FP semantics. Maybe we should change it to StateUpdate, or something similar.

**Comment by lippo97** [comment]
I suggest the following changes: 
- `Effect` --> `Update`
- `Game` --> `GameState`
- `SQuest` --> `Game`
