### ISSUE TITLE
Map declaration DSL

### ISSUE THREAD

**Issue by lippo97** [scalaquest/PPS-19-ScalaQuest#82]
It would be nice if we had a map declaration DSL, in order not to make mistakes when we declare the neighbors of every room.
I'm thinking of something like this:
```
  Floor(
    A <~>  B  <~> C  <~> D,
    E <~>  ## <~> ## <~> F <~> G <~> H <~> I,
    L <~>  M
  )

  Floor(
    N <~> O <~> P,
    Q
  )

  G ^ N
```
In which [A..N] are rooms and there are the following paths:
- A -> B -> C -> D -> F -> G -> H -> I
- A -> E -> L -> M
- N -> O -> P
- N -> Q
- G -> N

**Comment by maldins46** [comment]
![Wontfix](https://i.kym-cdn.com/photos/images/newsfeed/001/535/091/d97.jpg)
